default:
  # NOTE: This is pinned to 18.17 because 18.18 changed Unicode CLDR versions,
  # which changed number formatting for en-ZA, breaking tests.
  image: node:18.17.1-slim
  cache:
    # This uses a fixed cache key because Yarn has an immutable cache
    # mechanism, and automatically prunes dead items from the cache.
    - key: 'yarn-cache'
      paths:
        - .yarn
  before_script:
    - node --version
    - yarn --version

include:
  - 'packages/apiclient/.gitlab-ci.yml'
  - project: sanctumlabs/gitlab-ci
    file: templates/slack-notification.yml