default:
  image: oven/bun:1.0.3-alpine
  cache:
    - key: 'bun-cache'
      paths:
        - ~/.bun/install/cache
  before_script:
    - bun --version

stages:
  - lint
  - build
  - test
  - analyze
  - deploy
  - notification

include:
  - 'packages/apiclient/.gitlab-ci.yml'
  - project: sanctumlabs/tools/ci-workflows
    file: .gitlab/templates/slack-notification.yml
