nodeLinker: node-modules
compressionLevel: mixed
enableGlobalCache: false

logFilters:
  # Discard "Can't be found in the cache" warning spam
  - code: YN0013
    level: discard
  # Discard "Missing peer dependency" warnings.
  - code: YN0002
    level: discard
  # Discard warnings about mismatched versions of react/react-test-renderer/react-native/react-dom.
  - level: discard
    pattern: provides (@types/react|react-test-renderer|react|react-dom|react-native) * which doesn't satisfy
  # Discard an unmaintained dependency warning.
  - level: discard
    pattern: provides redux-persist * which doesn't satisfy
