.base-job:
  extends: .default-job
  before_script:
    - bun install
    - cd packages/apiclient

api-client-lint:
  extends: .base-job
  stage: lint
  interruptible: true
  needs: []
  script:
    - bun run lint

api-client-build:
  extends: .base-job
  stage: build
  interruptible: true
  needs:
    - api-client-lint
  script:
    - bun run build
  artifacts:
    untracked: false
    when: on_success
    expire_in: '30 days'
    paths:
      - ./packages/apiclient/dist

notification-success:
  extends: .notification-job
  variables:
    SLACK_TEXT: 'Build successful :smil:'
    SLACK_COLOR: 'good'
    SLACK_TITLE: 'Successful Build - ApiClient'
    SLACK_FALLBACK: 'Successful build - ApiClient'

notification-failure:
  extends: .notification-job
  when: on_failure
  variables:
    SLACK_TEXT: 'Build failed :sad:'
    SLACK_COLOR: 'danger'
    SLACK_TITLE: 'Build failure - ApiClient'
    SLACK_FALLBACK: 'Build failure - ApiClient'
